//this is acting as our temporary backend database
//structure for every element (building) is Name, Rooms (currentCapacity, maxCapacity, lastUpdated, facilities, isBookable, currentBooker), Usage

var details = [
  {
    'Name': 'Electrical Sciences Block',
    'Rooms': {
      'Foyer': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['Plug points', 'Board'],
        false,
      ],
      'Food Court': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['Plug points'],
        false,
      ],
      'Gazebo': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['Board'],
        false,
      ],
    },
    'Usage': [
      'Study',
      'Meetings',
    ],
  },
  {
    'Name': 'Classroom Complex',
    'Rooms': {
      'CRC101': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
      'CRC102': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
      'CRC103': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
      'CRC201': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "Quiz Club",
      ],
      'CRC202': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
      'CRC203': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
    },
    'Usage': [
      'Study',
      'Events',
    ],
  },
  {
    'Name': 'Humanity Sciences Block',
    'Rooms': {
      'Gandhi Hall': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors'],
        true,
        "No One",
      ],
      'Central Lecture Theatre': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors'],
        true,
        "Technical Society",
      ],
      'HSB133': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points'],
        true,
        "No One",
      ],
    },
    'Usage': [
      'Events',
      'Meetings',
    ],
  },
  {
    'Name': 'Ramanujan Block',
    'Rooms': {
      'RJN101': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
      'RJN102': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
      'RJN201': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
      'RJN202': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
    },
    'Usage': [
      'Events',
      'Meetings',
    ],
  },
  {
    'Name': 'Raman Block',
    'Rooms': {
      'RMN101': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
      'RMN102': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
      'RMN201': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
      'RMN202': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Projectors', 'Plug points', 'Board'],
        true,
        "No One",
      ],
    },
    'Usage': [
      'Events',
      'Meetings',
    ],
  },
  {
    'Name': 'Central Library',
    'Rooms': {
      'Ground Floor': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Plug points'],
        false,
      ],
      'First Floor': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Plug points'],
        false,
      ],
      'Second Floor': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Plug points'],
        false,
      ],
      'Third Floor': [
        10,
        100,
        DateTime.parse('1969-07-20 20:18:04Z'),
        ['AC', 'Plug points'],
        false,
      ],
    },
    'Usage': [
      'Study',
    ],
  },
];
